import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/providers';
import { AuthBtn } from './login/page';
import { ToggleTheme } from './_components/toggle-theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<main>
						<AuthBtn />
						<ToggleTheme />
						{children}
					</main>
				</Providers>
			</body>
		</html>
	);
}
